// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD15FkGZ_8FczSR0JvP87QCqgQS5vDhY08',
    appId: '1:720214753186:web:f02f4591f6e1e35184fcfb',
    messagingSenderId: '720214753186',
    projectId: 'foodsense-6f96e',
    authDomain: 'foodsense-6f96e.firebaseapp.com',
    storageBucket: 'foodsense-6f96e.firebasestorage.app',
    measurementId: 'G-TY2HTG0J10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfzQwQydvUNNMf2hvjGmQ_btGqqf3MGY',
    appId: '1:720214753186:android:3f161811764d4e9184fcfb',
    messagingSenderId: '720214753186',
    projectId: 'foodsense-6f96e',
    storageBucket: 'foodsense-6f96e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwRxfAgCgnbA1mYx_qyEwn7AZ8Hy9ivA',
    appId: '1:720214753186:ios:63fe98f5b764062d84fcfb',
    messagingSenderId: '720214753186',
    projectId: 'foodsense-6f96e',
    storageBucket: 'foodsense-6f96e.firebasestorage.app',
    iosBundleId: 'com.example.foodsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABwRxfAgCgnbA1mYx_qyEwn7AZ8Hy9ivA',
    appId: '1:720214753186:ios:63fe98f5b764062d84fcfb',
    messagingSenderId: '720214753186',
    projectId: 'foodsense-6f96e',
    storageBucket: 'foodsense-6f96e.firebasestorage.app',
    iosBundleId: 'com.example.foodsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD15FkGZ_8FczSR0JvP87QCqgQS5vDhY08',
    appId: '1:720214753186:web:6412ef714da4601a84fcfb',
    messagingSenderId: '720214753186',
    projectId: 'foodsense-6f96e',
    authDomain: 'foodsense-6f96e.firebaseapp.com',
    storageBucket: 'foodsense-6f96e.firebasestorage.app',
    measurementId: 'G-07KK26YBMG',
  );
}
